# # Example of docker-based Database Server.
# # Start using: docker-compose up -d
# # Stop using: docker-compose down
# version: '2.4'
# services:
#   app:
#     build: 
#       context: ..
#       dockerfile: ./docker/Dockerfile
#     volumes:
#       - .:/workspace
#     command: ["bash", "-c", "tail -f /dev/null"]
#     # depends_on:

version: '3.8'
services:
  posepipe:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: posepipe_dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=5
    volumes:
      - ..:/workspace
      - '/datajoint_external:/datajoint_external'
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      db:
        condition: service_healthy
  db:
    # image: datajoint/mysql:5.6
    # image: datajoint/mysql:5.7
    image: datajoint/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=pose
      # - DATAJOINT_DATABASE_CONFIG_MONITOR=FALSE # Enable MySQL config monitoring, auto reload
    ports:
      - "3306:3306"
    volumes:
      ## persist data across docker-compose up/down
      - ./data:/var/lib/mysql
      ## modify MySQL config
      # - ./my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 10